version: '3'
services:
  python:
    build:
      context: ./python
    volumes:
      - ./python:/app
    command: python /app/hello_world.py
  scala:
    build:
      context: ./scala
    volumes:
      - ./scala:/app
    command: scala HelloWorld.scala
  pyspark:
    build:
      context: ./pyspark
    volumes:
      - ./pyspark:/app
    command: spark-submit --master local[*] /app/app.py
